name: Fetch and process

on:
  schedule:
    - cron: "*/30 * * * *"
  repository_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Python requirements
      run: pip install -r requirements.txt

    - name: Fetch inbox feed, convert
      run: make run-feed

    - name: Generate history file
      run: make run-history
